sudo: false
language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - pypy
  - pypy3
install:
  - pip install -r tests/requirements.txt
  - pip install coveralls
script:
  - nosetests --with-coverage --cover-erase --cover-package=redminelib
after_success:
  - coveralls
